version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/designmypdf
      - CHROME_PATH=/usr/bin/google-chrome
      # Ajoutez ici vos variables B2 et autres variables d'environnement
      - B2_ACCOUNT_ID=${B2_ACCOUNT_ID}
      - B2_APPLICATION_KEY=${B2_APPLICATION_KEY}
      - B2_BUCKET_NAME=${B2_BUCKET_NAME}
    depends_on:
      - postgres
    volumes:
      - ./uploads:/app/uploads
      - ./tmp:/app/tmp

  postgres:
    image: postgres:15-alpine
    container_name: designPDF-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=designmypdf
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
